version: '2'
services: 
    data:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD: password
            - MYSQL_DATABASE: iot
            #- MYSQL_USER:
            #- MYSQL_PASSWORD:
            #- MYSQL_ALLOW_EMPTY_PASSWORD: no
            #- MYSQL_RANDOM_ROOT_PASSWORD: no
            - MYSQL_ONETIME_PASSWORD: yes
        expose:
            - "3306"
        ports:
            - "127.0.0.1:3306:3306"
        #volumes: 
            #- dataVolume01:/var/lib/mysql
    web:
        build: ./web/.

        links: 
            - data
volumes:
    - logVolume01: /tmp/docker/log
    #- dataVolume01: /tmp/docker/log

# once created, run this command
# docker-compose up -d --no-recreate .
# docker-compose up -d --force-recreate web 