version: '2'
services:
    temperature_data:
        image: hypriot/rpi-mysql:5.5
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: iot
        ports:
            - "3306:3306"
    temperature_web:
        build: ./web/.
        ports:
            - "3000:3000"
        links:
            - temperature_data
